# Simulation
episodes: 1000
step_limit: 50
random_seed: 42

# General
max_results_length: 10 # for plotting
images_path: "/home/ubuntu/spectrum_sharing/spectrum_sharing/Simulations/"
log_path: "/home/ubuntu/spectrum_sharing/spectrum_sharing/Logging/"
models_path: "/home/ubuntu/spectrum_sharing/spectrum_sharing/Models/"
buffer_path: "/home/ubuntu/spectrum_sharing/spectrum_sharing/Buffer/"
test_models_path: "/home/ubuntu/spectrum_sharing/spectrum_sharing/TestModels/"
scene_path: "/home/ubuntu/spectrum_sharing/spectrum_sharing/Scene/BRISTOL_3/"

# Scene and Sionna
num_rx: 20
max_depth: 5 # ray tracer depth
sharing_carrier_freq: 6465e6 # central carrier frequency in upper 6 GHz
primary_subcarrier_spacing: 15e3 # 5G numerology spacing
sharing_subcarrier_spacing: 30e3
primary_fft_size: 660 # approximately 10MHz per primary channel
sharing_fft_size: 3300 # approximately 100MHz sharing
batch_size: 1000 # essentially number of Monte Carlo simulations
cell_size: 2 # resolution of the coverage maps used for simulation

# Model and training
training_batch_size: 32 # in timesteps
training_epochs: 5
target_network_update_freq: 10 # in episodes
buffer_max_size: 1000000
gamma: 0.9 # how is future reward prioritised
epsilon_start: 1.0
epsilon_quick_start: 0.95 # for a preloaded model
epsilon_min: 0.15
epsilon_decay: 0.9995
learning_rate: 0.0001

# Normalisation ranges - SINR for example will be clipped to this range
min_power: 15.0 # in dBm, both inclusive
max_power: 50.0
min_sinr: -100 # in dB, constrains normalisation so keep low for sensitivity
max_sinr: 100

# Transmitters
transmitters:
    tx0:
        name: "tx0"
        position: [31, -106, 12] # [x,y,z] In the global scene coordinate system not the coverage map and utils system
        direction: [0, 0, 0]
        orientation: [0, 0, 0]
        color: [1, 0, 0]
        primary_power: 20.0
        sharing_power: 30.0
        min_power: 15.0
        max_power: 45.0
        state: 0
        look_at: [10, -50, 10]
        mu_pa: 0.4
        primary_carrier_freq: 3900e6

    tx1:
        name: "tx1"
        position: [-73, 126, 17]
        direction: [0, 0, 0]
        orientation: [0, 0, 0]
        color: [1, 0, 0]
        primary_power: 20.0
        sharing_power: 30.0
        min_power: 15.0
        max_power: 45.0
        state: 0
        look_at: [-50, 115, 10]
        mu_pa: 0.5
        primary_carrier_freq: 3700e6

    # tx2:
    #     name: "tx2"
    #     position: [0,0,0] # transmitter and receiver structure needs to be the same - may need to include Doppler
    #     direction: [0, 0, 0]
    #     orientation: [0, 0, 0]
    #     color: [1, 0, 0]
    #     primary_power: 21.0
    #     sharing_power: 21.0
    #     look_at: [0, 0, 0]
    #     mu_pa: 0.2
    #     primary_carrier_freq: 5000e6